name: home_assignment_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/songs/Sleep_Token_Emergence.mp3
    - assets/songs/Super_Mario_Bros_Theme_Song.mp3
  uses-material-design: true
